esphome:
  name: samsung-ac-ir-remote

esp8266:
  board: esp01_1m

logger:
  baud_rate: 0

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "samsung-ac-ir-remote Fallback Hotspot"
    password: "0000"

web_server:
  port: 80

external_components:
  - source:
      type: git
      url: https://github.com/rozh1/esphome-samsung-ac-ir

sensor:
  # External temperature sensor from Home Assistant 
  - platform: homeassistant
    id: current_temperature
    entity_id: ${temperature_sensor}

climate:
  - platform: samsung_ac
    sensor_id: current_temperature
    pin: 3 # Pin with IR led
    name: "AC Samsung"